services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - quote-network
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN           # chown log/cache dirs to nginx user
      - SETUID          # ← master process drops to nginx user
      - SETGID          # drop group too
      - NET_BIND_SERVICE # bind to port 80 (< 1024)

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://quoteuser:quotepass@db:5432/quotes
      REDIS_HOST: redis
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
    networks:
      - quote-network
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL


  worker:
    build: .
    command: celery -A app.worker worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://quoteuser:quotepass@db:5432/quotes
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - quote-network
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: quoteuser
      POSTGRES_PASSWORD: quotepass
      POSTGRES_DB: quotes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quoteuser -d quotes"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quote-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN        # chown data directory to postgres user
      - DAC_OVERRIDE # read/write files regardless of ownership
      - FOWNER       # bypass permission checks as file owner
      - SETGID       # switch group from root → postgres
      - SETUID       # ← switch user from root → postgres (was missing)
        
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - quote-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - DAC_OVERRIDE



networks:
  quote-network:
    driver: bridge
volumes:
  postgres-data: