services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://quoteuser:quotepass@db:5432/quotes
    depends_on:
        db:
          condition: service_healthy
    networks:
      - quote-network
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: quoteuser
      POSTGRES_PASSWORD: quotepass
      POSTGRES_DB: quotes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quoteuser -d quotes"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quote-network

networks:
  quote-network:
    driver: bridge
volumes:
  postgres-data: