events {}

http {
    upstream api_backend {
        server api:8000;
    }

    server {
        listen 80;
        resolver 127.0.0.11 valid=10s;
        set $api_upstream http://api:8000;

        location / {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}